### ISSUE TITLE
Is anything wrong with cookies? 

### ISSUE THREAD

**Issue by blackbuzz4rd** [SimpleBrowserDotNet/SimpleBrowser#200] opened 2018-02-18 10:34 UTC
I know SB can manage cookies automatically. But I'm getting this Cookies Disabled error [Error](https://imgur.com/a/5MgEh)
I used this [link](https://goo.gl/KQr6ux) to login.

**Comment by kevingy** [comment] 2018-02-18 22:04
This likely caused by SimpleBrowser not supporting JavaScript, rather than there being something wrong with cookies. There are lots of sites that use JavaScript to create cookies. When the site can't find the cookie that it just attempted to create, it reports it as a cookie error - making the incorrect assumption that _all_ web browsers support JavaScript. I haven't attempted to use Facebook with SimpleBrowser (or, for that matter, any browser, as I detest Facebook and most of its social media ilk).

To my knowledge, there is no known issue with cookies that has been definitively identified.

**Comment by kevingy** [comment] 2018-03-29 17:45
I'm going to close this issue as "unable to reproduce". If that is not the case, please reply and re-open the issue.

**Closed by kevingy** 2018-03-29 17:45 UTC
