### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by kaspars-ozols** [SimpleBrowserDotNet/SimpleBrowser#172] opened 2016-05-27 12:44 UTC
HTML parsing does not work correctly if markup contains attributes with HTML tokens in their value. 

For example:
```

<a href="#" rel="tooltip" id="c7063a12-5f4c-45fb-b116-e70fddb691b2" data-placement="top" data-original-title="<div class='custom_tooltip'><p>DO NOT fill in here!</p>
<p>Make a short and indicative prefix. The prefix will identify the company and it's sub users.</p>
<p>EXAMPLE: Gooogle employees/users will get the following structure in their username: g! + alias (company prefix + e.g. their initials).</p></div>">?</a>

```
XDocument is created, but it does not match HTML structure. In my case, `div` element was closed too early which caused `form` element to close as well. Therefore not all the input fields were submitted. Can provide full markup in private message, haven't added full sample as it contains details I don't want to make public.

**Comment by kevingy** [comment] 2016-05-27 13:11
You are correct, SimpleBrowser does not yet handle this case of malformed HTML. Technically, this is a duplicate of issue #80, with different HTML that needs to be encoded.

**Comment by kevingy** [comment] 2016-05-30 01:40
I'm going to close this issue as a duplicate. This issue will be referenced in issue #80.

**Closed by kevingy** 2016-05-30 01:40 UTC
