### ISSUE TITLE
Mono SSL Certificates Issue

### ISSUE THREAD

**Issue by pixelport** [SimpleBrowserDotNet/SimpleBrowser#167] opened 2016-03-10 12:04 UTC
Cookies doesn't seem to be set via Set-Cookie Http Field.

How to reproduce:

```
var browser = new Browser
{
    UserAgent = "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10"
};
browser.Navigate("https://httpbin.org/cookies/set?name=value");
browser.Navigate("https://httpbin.org/cookies");

Console.WriteLine(browser.CurrentHtml);
```

Output is empty. A normal browser will output: 

```
{
    "cookies": {
        "name": "value"
    }
}
```

Any Ideas how to fix this?

**Comment by pixelport** [comment] 2016-03-13 15:42
Thank you!

**Comment by kevingy** [comment] 2016-03-14 12:09
Using the code you provide, I'm unable to reproduce this issue:

![image](https://cloud.githubusercontent.com/assets/411556/13744030/c85fe0ce-e9bb-11e5-83c2-06e403fccb60.png)

**Comment by pixelport** [comment] 2016-03-14 20:00
Interesting.

I am using mono under Linux. SimpleWebBrowserDotNet seems to be able to parse cookies of non-https sites. When you switch https:// to http:// it works. The problem seems only to only occur with https and mono.

What could be the problem?

**Comment by kevingy** [comment] 2016-03-15 12:52
Very interesting, indeed. It is different between Mono and Windows. Additionally, it's not a cookie problem at all. On Mono, when SimpleBrowser tries to send the encrypted request to httpbin.org, the navigation fails. It's throwing this exception:

> {System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.   at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0    at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    --- End of inner exception stack trace ---   at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0    at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0    at SimpleBrowser.NetwoOn Mono, when SimpleBrowser tries to send the encrypted request to httpbin.org, it's throwing rk.WebRequestWrapper.GetResponse () [0x00000] in /home/kevingy/dev/SimpleBrowser/SimpleBrowser/Network/WebRequestWrapper.cs:26    at SimpleBrowser.Browser.DoRequest (System.Uri uri, System.String method, System.Collections.Specialized.NameValueCollection userVariables, System.String postData, System.String contentType, System.String encodingType, Int32 timeoutMilliseconds) [0x00416] in /home/kevingy/dev/SimpleBrowser/SimpleBrowser/Browser.cs:865 }

At first, I thought this was an issue accessing https in general, but https://www.google.com works. After some research, it looks like Mono doesn't trust the httpbin.org SSL certificate. Windows handles all of this for the user. So far, all of the suggested solutions I have come across have not worked.

I'll keep working it, but that's all the time I have for now. I'll be back.

**Comment by kevingy** [comment] 2016-03-16 12:24
I've made some progress, kinda. I think it's a Mono Certificates issue, but I have been unable to confirm. This page offers insight and four solutions:

http://www.mono-project.com/docs/faq/security/

The page starts off by saying that Mono doesn't trust anyone. (Which is not true, because it trusted Google.) The page continues, "You can confirm this by using the tlstest tool (needs Mono >= 3.4.0). It prints an error if something is wrong." Unfortunately, the most up to date Mono version in my Debian installation (which I am unable to upgrade at this time) is 3.0.2.

Of those four offered solutions, I couldn't get any to work.
1. The first option requires Mono 3.12.0 or better. Again, my Mono version is ancient.
2. The second option is to "implement a ICertificatePolicy class". I think this is what they are doing in tlstest. I couldn't get this to compile, probably because of my Mono version.
3. The third option is "use the certmgr.exe tool (included in Mono)". I attempted to do this, but the tool throws the exact same exception as SimpleBrowser
4. The fourth option is "use the mozroots.exe tool". I was unable to try this. I do not have (and will not have) Firefox installed. This option requires Firefox.

This is where I ask you for help. What is your Mono version? If your version is more up to date, can you run the tlstool or cert-sync? Do you have Firefox installed? If so, can you run mozroots.exe?

I have another machine here that I can reinitialize and install a newer Linux and Mono, but that will take some time. It might have to wait until the weekend before I can devote that much time to the task.

**Comment by pixelport** [comment] 2016-03-16 15:23
Sounds great! I am using mono 4.3.2 and firefox 44.02 on linux mint.

Started with testing urls with [tlstest.exe](https://raw.githubusercontent.com/mono/mono/master/mcs/class/Mono.Security/Test/tools/tlstest/tlstest.cs). I noticed that versions of https://google.com, https://yahoo.com and https://facebook.com all work only https://httpbin.org throws an exception. In Firefox and Chrome the cert of https://httpbin.org does get accepted. Firefox and Chrome doesn't use the system wide linux certs. They seem to have their own lists.

I tried cert-sync. Didn't work. Maybe the https://httpbin.org cert isn't included in the system certificate list. So I tried the mozroots.exe tool. You don't need firefox for it. I added all the certs but It doesn't work either. "mono tlstest.exe https://httpbin.org" still does throw an exception. 

I also tried if I could import any specific cert. I exported the cert of https://httpbin.org via firefox and then imported it via "sudo certmgr -add -c -v -m Trust httpbin.crt". The mono certificate manager outputs: "1 certificate(s) added to store Trust." But the exception still occurs. The httpbin cert doesn't seem to be anything unusual. It's signed from COMODO CA Limited.

Please take a look at https://github.com/SimpleBrowserDotNet/SimpleBrowser/blob/master/SimpleBrowser/Browser.cs#L51 Shouldn't line 51 allow all certs? 









https://github.com/SimpleBrowserDotNet/SimpleBrowser/blob/master/SimpleBrowser/Browser.cs#L51

**Comment by kevingy** [comment] 2016-03-16 18:05
```
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
```

This should work, but wasn't in my testing. That said, it is not coded exactly the way the Mono says to do it. I'll give it a try next time I'm able.

**Comment by kevingy** [comment] 2016-03-23 11:30
Actually, that should not work in any .NET version beyond 2.0 because of changes made by Microsoft to tighten .NET security. That code is obsolete and should be removed.

I'm going to set up a virtual machine today with the newest versions of Debian and Mono to trouble shoot this problem further.

**Comment by kevingy** [comment] 2016-03-23 15:39
I've worked with this issue to say the following with a reasonable amount of confidence: "This is not a SimpleBrowser issue." The rest is conjecture, based upon findings.

I suspect that the issue is in one of two places:
1. There is a code issue in Mono. Using the documentation, tools, and source provided by Mono, I'm getting the same error that I'm getting out of SimpleBrowser.
2. The current Debian distribution does not include ca-certificates-mono. According to Mono, there is a tool in there that will act as the Mono equivalent of the Windows certificate store. If so, that may solve this problem.

This, however, is as far as I am willing to work on this problem at this time. I will return to it when and if a new version of Mono is added to the current or future Debian distributions or the ca-certificates-mono package is added to the current or future Debian distribution. If I get really bored, I might try a different Linux, but for now, that's off the table.

Leaving the issue open until then or for someone else to work on.

**Comment by pixelport** [comment] 2016-03-25 18:23
Thank you!

**Comment by kevingy** [comment] 2019-05-14 16:53
In my work on Issue #220, I wonder now if SSL vs TLS was the issue then. I'll try to set up another test with my newer Debian/Mono installation to see what happens with the changes for #220.

**Comment by kevingy** [comment] 2019-08-25 00:16
This issue is fixed in the forthcoming SimpleBrowser upgrade to .NET Standard 2.0, built using VSCode on Debian 10 (Issue #222).

**Closed by kevingy** 2019-08-25 00:16 UTC
