### ISSUE TITLE
Download Scenario

### ISSUE THREAD

**Issue by ozang** [SimpleBrowserDotNet/SimpleBrowser#175] opened 2016-05-28 10:07 UTC
Hi,

I searched but could not find. I want to save the downloaded file after clicking an icon. Is this scenario possible in SimpleBrowser?

**Comment by kevingy** [comment] 2016-05-28 14:33
File downloads are not currently supported.

This issue is being closed as a duplicate of issue #37.

**Closed by kevingy** 2016-05-28 14:33 UTC
