### ISSUE TITLE
Download file from button click that doesn't have a href

### ISSUE THREAD

**Issue by jairofranchi** [SimpleBrowserDotNet/SimpleBrowser#158] opened 2015-12-03 11:59 UTC
Hi Kevin. I am using the SimpleBrowser and my question is how I can download a file that on it original page just downloads the file automatically when clicking in the button. In the code I connect to the page using the certificate, it works fine and then I send the information necessary to the form and when I click in the download file it just says in the Debug that is Unauthorized and nothing happens, and looking to the element in the page I can't found anything that I could pass to get the file, it does not have a HREF attribute or shows any different URL when downloading the file. How is possible that I get the file from the page? The file to download is in PDF format.

**Comment by kevingy** [comment] 2015-12-08 00:10
From your description of the problem, there are multiple problems occurring at once:
1. Authentication/Authorization: If you're getting Unauthorized when you send the request, that's the first problem. What kind of authentication or authorization does the site that you are attempting to access use.
2. It sounds like the file might be delivered via execution of JavaScript. If you're not seeing a URL or some other method for making the request that would start the download, that's suspect.
3. Finally, and this really is the kicker, SimpleBrowser does not yet handle binary downloads. Therefore, even if you were able to figure out 1 and 2 above, SimpleBrowser would not be able to download and save the PDF.

It's coming, but not ready yet.

**Comment by kevingy** [comment] 2016-02-25 13:48
Closing as a duplicate of Issue #37

**Closed by kevingy** 2016-02-25 13:48 UTC
