### ISSUE TITLE
Where file is placed when download the file from download link?

### ISSUE THREAD

**Issue by jairofranchi** [SimpleBrowserDotNet/SimpleBrowser#149] opened 2015-10-15 11:55 UTC
Hi Kevin. One question, I working in an automation that access a website and then I download some files from it. My question is, I'm downloading the file from the "href" attribute of the link, it works fine in this case but moreover I need to set the file as already clicked and to this happen, I need to click in the link then the line where it is in the website changes it color, so if I just click in the link I notice that it takes a time to respond as it was downloading, but it really downloads the file, and if yes, where the file goes?

**Comment by kevingy** [comment] 2015-10-16 18:38
Unfortunately, SimpleBrowser does not support saving files to disk. Any file requested is read into a string then passed to the HTML parser. After parsing (whether successful or not), the string is deleted.

I have been too busy at work these last four months to do any recreational coding. After November 1, I should have time to implement this. There have been many requests for it.

Technically, this issue is a duplicate of Issue #37 (poorly titled "binary response").

**Comment by kevingy** [comment] 2015-11-18 03:19
Closing this issue in favor of Issue #37. Work on that issue will start soon.

**Closed by kevingy** 2015-11-18 03:19 UTC
