### ISSUE TITLE
Dummy-Url error using SetContent()

### ISSUE THREAD

**Issue by franci2312** [SimpleBrowserDotNet/SimpleBrowser#217] opened 2018-10-14 13:02 UTC
When I use SetContent() An error occours "Could not recognize namespace Dummy-url-to-use.with". The problem is caused by the SetContent method in browser.cs  . I suggest removing the dummy url that makes setcontent() impossible to use in some cases.

**Comment by kevingy** [comment] 2019-05-11 19:48
@franci2312 I'm working on this issue today. I'm not going to remove the dummy url. I'd like to replace it with something that makes more sense. I'm considering using the app URI scheme, for example "app://content". This works in my testing, but the dummy URL works too.

How are you testing to get the error with the unrecognized namespace? I'd like to perform that same test to see if my fix worked.

**Comment by kevingy** [comment] 2019-05-14 13:39
@franci2312 I still can't reproduce this error. What are the test cases that cause this error?

**Comment by kevingy** [comment] 2019-05-28 11:39
Fixed in master

**Closed by kevingy** 2019-05-28 11:39 UTC
