### ISSUE TITLE
Problem with referer

### ISSUE THREAD

**Issue by xpagedeveloper** [SimpleBrowserDotNet/SimpleBrowser#185] opened 2017-07-06 15:05 UTC
I have a strange problem that I have diagnosed using fiddler.
I get an error connecting to a service I'm tying to use.
The only things I can see is that the referer beeing strange when using simple browser
This is parts of the referer using simple browser
TARGET=https:%252f%252fserver.com%252fliveAdmin%253fOpen%2526langCode%253den_US

The same using Chrome
TARGET=https%3a%2f%2fserver.com%2fliveAdmin.nsf%3fOpen%26langCode%3den_US

Anybody have any clues how to fix this seams like Simple browsers referer beeing converted to Unicode or something?

**Comment by kevingy** [comment] 2017-07-06 18:27
Using the sample program, I'm not seeing the extra characters in the referer header. Here's a capture from Fiddler:

![image](https://user-images.githubusercontent.com/411556/27925995-cc354c94-6254-11e7-83b7-f60a480b1b50.png)

So, what is "TARGET"? "TARGET" is not referer. There isn't a HTTP header called "TARGET". The text you are showing for TARGET is URL encoded - actually, encoded twice in the case of the output from SimpleBrowser. A referrer is sent in plain (non-URL encoded) text.

**Comment by xpagedeveloper** [comment] 2017-07-06 21:47
if I use navigate with postdata to simulate a form post. I see this in the next request after this.
the post data contains a field called target.
is there a better way to do a form post if there isn't a submit button in the form

**Comment by kevingy** [comment] 2017-07-07 02:26
There is a much better way to submit a form. The FormElement class has a SubmitForm() member. You can either call FormElement.SubmitForm() or SubmitForm() on any FormElement-derived class - including InputElement, CheckboxInputElement, TextAreaElement, and so on.

I don't have insight into what the form looks like, but there must be a form element in the form named TARGET. I can say without a doubt that SimpleBrowser isn't adding something to the form post that's not present in the form. Looking at server.com, it looks like the web site you are working on is under construction. Can you provide the code of the page containing the form - or at least just the HTML <form> element and its descendants? It's really hard to try to debug something blindly.

**Comment by kevingy** [comment] 2017-07-07 02:34
For more information on working with forms, see the SimpleBrowser Wiki:

https://github.com/SimpleBrowserDotNet/SimpleBrowser/wiki/Tutorial#submitting-forms

This might solve your problem.

**Comment by xpagedeveloper** [comment] 2017-07-08 14:08
It gave me the same result.
I will try setup a server that I can test this more on but I see the same thing if I do this using simpel browser
    browser.Navigate("https://posttestserver.com/post.php?Target=https:%2f%2fadmin.server.com%2fgetDat%3fOpen%26custId%3d1%26langCode%3den_US");
   browser.Navigate("https://posttestserver.com/");

**Comment by kevingy** [comment] 2017-07-10 12:39
I'm still not able to reproduce this,

I navigated to posttestserver.com, I get this result:
> Successfully dumped 0 post variables. View it at http://www.posttestserver.com/data/2017/07/10/12.17.481450289437 No Post body.

That seems incredibly unhelpful. I prefer to use symlink.dk:
http://symlink.dk/code/php/submit/?Target=https:%2f%2fadmin.server.com%2fgetDat%3fOpen%26custId%3d1%26langCode%3den_US

![image](https://user-images.githubusercontent.com/411556/28017883-0d4c5af0-6549-11e7-87b4-ac04302d7b13.png)

If I use Chrome or SimpleBrowser, I get the same result from Fiddler:
![image](https://user-images.githubusercontent.com/411556/28017975-67d48010-6549-11e7-9621-150d8c56473b.png)

Regardless of using posttestserver.com or symlink.dk, I don't see the query string value from the first navigation in the second navigation. Can you send me a screen capture from Fiddler showing the value of Target in the second navigation?

**Comment by kevingy** [comment] 2017-07-19 14:23
@xpagedeveloper Are you still having an issue with this? I haven't heard from you in a while.

**Comment by kevingy** [comment] 2017-12-05 21:01
Since I wasn't ever able to reproduce the issue and @xpagedeveloper hasn't replied in 5 months, I'm closing this issue. If this becomes relevant again, the issue can be reopened.

**Closed by kevingy** 2017-12-05 21:01 UTC
